language: python
python:
  - 3.8
  - "pypy3"
install:
  - pip install -r requirements.txt
script:
  - make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: flosstudio.schema.json
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
